### ISSUE TITLE
Frequent reoccuring errors requiring piped_backend restart on piped.garudalinux.org

### ISSUE THREAD

**Issue by dr460nf1r3** [TeamPiped/Piped#2020]
### Describe the bug

I'm running the Piped instance piped.garudalinux.org which often requires a restart of the piped backend container in order to work again. I'm not fully sure what the issue is at this point, but this is how it looks like when accessing the instance (using Libretube it just reports there is an error with this instance): 

![image](https://user-images.githubusercontent.com/12834713/214877676-8878f01f-32d3-4a1f-9dfa-7fdcd392c789.png)

Since I'm not sure when the bug actually started to occur (mostly notice it only when getting reports or using Libretube), I uploaded the complete container log below.

### To Reproduce

Since I already restarted the instance, the error doesn't occur right now. I haven't found the pattern to reproduce it yet. 

### Expected behavior

Have the videos displayed correctly, so regular use can happen.

### Logs/Errors

[Find the backend logs here](https://cloud.garudalinux.org/s/yiW96TZabdsHDWE).
No apparent web console errors were observed. 

### Browser, and OS with Version.

Happens with every browser and Libretube as well. 

### Additional context

The particular docker-compose setup in use can be found at the infra repo: https://github.com/garuda-linux/infrastructure-nix/blob/main/nix/docker-compose/web-dragon/docker-compose.yml#L188

It lives in a Proxmox LXC container running NixOS (12cores/20GB RAM, so missing resources definitely shouldn't be an issue. I also noticed that, when the issue is present, very high CPU usage occurs due to the backend: 

![image](https://user-images.githubusercontent.com/12834713/214880291-b6fcccec-558c-4b8b-a3fa-9b5017a1451b.png)

**Comment by bbsixzz** [comment]
I've also noticed the buffer is super slow using [Yattee ](https://github.com/yattee/yattee), not usable anymore.

**Comment by FireMasterK** [comment]
I suspect that your instance might be hampered by bots since there are a lot of network timeouts to Google's servers from the logs.

I've started a new idea to move the networking stack in Piped to Rust via JNI to move away from OkHttp, which is written in Kotlin/Java and should be more efficient. I believe this could also fix the timeout issues. This could allow us to get support for HTTP/3 in the future if reqwest supports it. The new repository at https://github.com/TeamPiped/reqwest4j will be updated once it is ready.

**Comment by dr460nf1r3** [comment]
I just had a look into the logs, though I couldn't find any obvious bot traffic. Though I noticed something else - the path `/opensearch/suggestions` gets requested quite a lot compared to other paths (around 0,4/5,3M requests). Could it be that the search sends too many requests? 

![image](https://user-images.githubusercontent.com/12834713/215328174-b941abf9-b757-4190-bd94-5e6b888f60e7.png)

I'm definitely looking forward to the Rust rewrite. Sounds like a great addition to Piped!

**Comment by FireMasterK** [comment]
> /opensearch/suggestions gets requested quite a lot compared to other paths (around 0,5/5,3M requests). Could it be that the search sends too many requests?

I doubt that, that's normal behavior, I suspect the `/streams/` endpoint, since that was attacked by bots on the official instance.

**Comment by FireMasterK** [comment]
The networking stack is now written in Rust! :tada:
Let me know how things are once you update your instance.

I also noticed that you're not using the new proxy written in rust either:
https://github.com/garuda-linux/infrastructure-nix/blob/6fecd6f830d6680ee3e9d371e62b0c55b95f0be4/nix/docker-compose/web-dragon/docker-compose.yml#L233

You should change that too.

**Comment by FireMasterK** [comment]
Another thing I've noticed is that your instance doesn't seem to be caching API responses, do you have a page rule with Cache Everything enabled on Cloudflare?

**Comment by dr460nf1r3** [comment]
Alright! Very cool you got it done this quickly 🥳 Updated the containers and looking at the logs, we are indeed using the new backend now :) 

As for the new rust proxy - I just added it in https://github.com/garuda-linux/infrastructure-nix/commit/35d86ea63d5d101f0d1b3ca8cafd114fa5f2729e! Thanks for making me aware 🥇 

We do have the following rule active (apart from another cache all one):
```
piped*.garudalinux.org/*
Security Level: High, Cache Level: Bypass, Cache Deception Armor: Off, Origin Cache Control: On
```
Anything you'd suggest doing different?

**Comment by FireMasterK** [comment]
> piped*.garudalinux.org/*
> Cache Level: Bypass

You should change this to Cache Everything, since this matches the proxy and API (correctly as expected).

**Comment by Insprill** [comment]
Correct me if I'm wrong, but changing it to Cache Everything also caches HTML meaning people's feeds, history, preferences, etc would get cached ([source](https://developers.cloudflare.com/cache/how-to/create-page-rules/#cache-everything)).

**Comment by FireMasterK** [comment]
We also enable `Origin Cache Control`, which allows the Origin, which in this case the backend sends `Cache-Control` headers to control the cache per route/scenario.

The front end is entirely static, so it doesn't matter even if everything is cached.

**Comment by dr460nf1r3** [comment]
> > piped*.garudalinux.org/*
> > Cache Level: Bypass
> 
> You should change this to Cache Everything, since this matches the proxy and API (correctly as expected).

This is implemented since you mentioned it and seems to work well so far. 

One thing I noticed after implementing the changes is that the new Piped proxy seems to break thumbnail and video loading for some reason - for now the change has been reverted until I have time to look into this at the weekend.

**Comment by dr460nf1r3** [comment]
As feedback after a week: the backend issues are resolved by the new backend. There weren't any more reports and I didn't notice playback issues when using it, so that's great!

**Comment by dr460nf1r3** [comment]
@bbsixzz We currently have an issue with the storage space filling up with countless coredumps (170GB+) of the Piped backend, so we had to take it down. Real life happens and I still need to investigate the root cause.

**Comment by FarisZR** [comment]
Hi, I am also facing similar issues of Timeouts, that suddenly started today (piped.aosus.org)
```
An error occoured in the path: /streams/NJnWB8UX3rs
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at me.kavin.piped.server.handlers.StreamHandlers.streamsResponse(StreamHandlers.java:133)
	at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$11(ServerLauncher.java:138)
	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(Unknown Source)
	at java.base/java.lang.VirtualThread.run(Unknown Source)
	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(Unknown Source)
	at java.base/jdk.internal.vm.Continuation.enter0(Unknown Source)
	at java.base/jdk.internal.vm.Continuation.enter(Unknown Source)
```
 
 compose running behind Caddy:
 ```
 version: "3"

networks:
  default:
  web:
    external: true

services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest
    restart: always
    container_name: pipedfrontend
    depends_on:
      - piped
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/api.piped.aosus.org/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    networks:
      web:

  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    container_name: piped-proxy
    restart: always
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket

  piped:
    image: 1337kavin/piped:latest
    container_name: piped
    restart: always
    configs:
      - source: piped
        target: /app/config.properties
    depends_on:
      - postgres
      
  nginx:
    image: nginx:mainline-alpine
    restart: always
    container_name: piped-nginx
    volumes:
      - piped-proxy:/var/run/ytproxy
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
      - source: pipedapi
        target: /etc/nginx/conf.d/pipedapi.conf
      - source: pipedproxy
        target: /etc/nginx/conf.d/pipedproxy.conf
      - source: pipedfrontend
        target: /etc/nginx/conf.d/pipedfrontend.conf
      - source: ytproxy
        target: /etc/nginx/snippets/ytproxy.conf
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend
    networks:
      - default
      - web

  postgres:
    image: postgres:14-alpine
    container_name: piped-postgres
    restart: always
    volumes:
      - /home/ubuntu/piped/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=xxxxxx

volumes:
  piped-proxy:
    external: true

configs:
  nginx:
    file: /home/ubuntu/piped/config/nginx.conf
  pipedapi:
    file: /home/ubuntu/piped/config/pipedapi.conf
  pipedproxy:
    file: /home/ubuntu/piped/config/pipedproxy.conf
  pipedfrontend:
    file: /home/ubuntu/piped/config/pipedfrontend.conf
  ytproxy:
    file: /home/ubuntu/piped/config/ytproxy.conf
  piped: 
    file: /home/ubuntu/piped/config/config.properties
    ```
