### ISSUE TITLE
Simple docker-compose

### ISSUE THREAD

**Issue by tiritibambix** [TeamPiped/Piped#2508]
### Describe your question

Hello.

Forgive my ignorance as I'm new to this. I was reading the docs for self hosting, and each config contains a caddy / nginx config.

I wouldn't need these as I'm already running nginx proxy manager as a reverse proxy.

How could I simply install piped without caddy or nginx using a simple docker-compose ?

Thanks for your help.

**Comment by FireMasterK** [comment]
You could choose the nginx version, it's for installations that already have a reverse proxy.

**Comment by tiritibambix** [comment]
> You could choose the nginx version, it's for installations that already have a reverse proxy.

Oh, I must have misunderstood the docs then. Thank you, I'll have a look

**Comment by FireMasterK** [comment]
The docs need to updated to make things more clear, but that's an another issue altogether!

**Comment by tiritibambix** [comment]
> The docs need to updated to make things more clear, but that's an another issue altogether!

Oh, that'd be great : ) There are a lot of instructions that I don't understand and why I can't just use a simple docker-compose.

**Comment by tiritibambix** [comment]
For anyone interested, here it is:

```
version: "3"

services:
  backend:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - piped:/app/config.properties
    depends_on:
      - postgres
    networks:
      - piped

  piped:
    image: 1337kavin/piped-frontend
    restart: unless-stopped
    ports:
      - 10103:80 #or whatever:80
    networks:
      - piped
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=changeme
    networks:
      - piped

volumes:
  piped:
  db:
networks:
  piped:
```
