### ISSUE TITLE
Login as admin

### ISSUE THREAD

**Issue by tiritibambix** [TeamPiped/Piped#2512]
### Describe your question

Hello,

I just installed piped and I was wondering if I can login as admin and if there are options to disable registration and a possibility for manual user creation ?

I see nothing in the docs.

Thanks for your help.

**Comment by tiritibambix** [comment]
Can `DISABLE_REGISTRATION:true` be an environment variable if I use a docker-copose.yml file to deploy it ?

**Comment by tiritibambix** [comment]
I'm sorry for asking, I feel a bit dumb, but I can't get it to work.

I use this docker-compose:
```
version: "3"

services:
  backend:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Piped:/app/config.properties
    depends_on:
      - postgres
    networks:
      - piped

  piped:
    image: 1337kavin/piped-frontend
    restart: unless-stopped
    ports:
      - 10103:80
    networks:
      - piped
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Piped/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=01664892ganjah12

    networks:
      - piped

volumes:
  piped:
  db:
networks:
  piped:
```
I tried adding the variable in different places but Registration is still possible.

I edited `config.properties` with `DISABLE_REGISTRATION:true` and still no luck.

Is there something I'm missing ?
