### ISSUE TITLE
Self hosted instance can't load trending, search or load video

### ISSUE THREAD

**Issue by cronyakatsuki** [TeamPiped/Piped#2527]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Couple days back I reported the first issue I had that ended pup being the piped backend was constantly restarting.

Now again I'm experience an issue where I can't search or do anything on the instance.

### To Reproduce

...

### Expected behavior

To be able to search, check trending, load videos, ...

### Logs/Errors

Here are the [logs](https://pastebin.com/raw/xbAkYTL1) taken with `docker-compose logs -f`

### Additional context

There is also the issue of piped backend starting to use 100% of cpu for some time after any action like loading homepage, searching, ..

Installed via docker on a debian 11 vps.

Instance is hosted at https://piped.cronyakatsuki.xyz

**Comment by FireMasterK** [comment]
It looks like your backend is continuously crashing since it can't establish a connection to postgres. Have you modified any of the `docker-compose` / config files?

**Comment by cronyakatsuki** [comment]
```yml
version: "3"

services:
    pipedfrontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        container_name: piped-frontend
        entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/pipedapi.cronyakatsuki.xyz/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        environment:
            - UDS=1
        volumes:
            - piped-proxy:/app/socket
        container_name: piped-proxy
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        volumes:
            - ./config/config.properties:/app/config.properties:ro
        depends_on:
            - postgres-piped
        container_name: piped-backend
    nginx:
        image: nginx:mainline-alpine
        restart: unless-stopped
        ports:
            - "8280:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
            - ./config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
            - ./config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
            - ./config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
            - piped-proxy:/var/run/ytproxy
        container_name: nginx
        depends_on:
            - piped
            - piped-proxy
            - pipedfrontend
    postgres-piped:
        image: postgres:15
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: postgres-piped
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/timezone:/etc/timezone:ro
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_INCLUDE_RESTARTING=true
        container_name: watchtower
        command: piped-frontend piped-backend piped-proxy varnish nginx postgres-piped watchtower
volumes:
    piped-proxy: null
```
This is what my docker-compose looks like, I had to change the prosody container name since I already have one running for another service and wouldn't be suprised I did something wrong while doing it.
