### ISSUE TITLE
How to selfhost with Cloudflare Tunnel?

### ISSUE THREAD

**Issue by whaler-ragweed** [TeamPiped/Piped#2600]
### Describe your question

I'm new to selfhosting. Currently I use Cloudflare Tunnel for my selfhosted services (with Docker Compose). Can I use it instead of Caddy or Nginx?

EDIT: I run this compose file and it works without backend and database. Would it cause any problem?

```
services:
  piped:
    image: 1337kavin/piped-frontend
    container_name: piped
    restart: unless-stopped
    ports:
      - 51609:80
```
