### ISSUE TITLE
Fix comment formatting

### ISSUE THREAD

**Issue by r-a-y** [TeamPiped/Piped#267]
First of all, just wanted to say congrats on the project. Loads way faster than Invidious!

The one thing that stood out was how the comment user avatar and comment were on separate rows. I'm currently using the following user CSS so the comment avatar is floated to the left, followed by the comment, but feel free to adapt it to work with Piped:

```CSS
div.uk-align-left div[align="left"] {float:left; width:90px; word-wrap:break-word;}

div.uk-align-left p {float:left; margin-left:1em; margin-top:0; width:calc(100% - 1em - 90px)}

div.uk-align-left p + div {clear:both;}
```
