### ISSUE TITLE
piped + nginx proxy manager

### ISSUE THREAD

**Issue by purashy** [TeamPiped/Piped#2694]
> Apologies, this should have gone to `questions`, not `bugs`.

### Describe the bug

I am not quite sure how to describe it. I am kind of lost on how to get this working.

Basically, I am using docker-compose. I want to run piped (completely selfhosted) on docker, and reverse proxied via nginx proxy manager.

This is a complete new installation of piped. However when i try to create a new user, it says "The username you have used is already taken.". Which leads me to believe that perhaps i am not running my own instance but only the front-end, and it is using a public instance perhaps?

Below are my configs and what not:

**Docker-Compose:**

```yaml
version: "3"
services:
  backend:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - /home/user/config.properties:/app/config.properties
    depends_on:
      - postgres

  piped:
    image: 1337kavin/piped-frontend
    restart: unless-stopped
    ports:
      - 9005:80
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - /home/user/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
```

**config.properties:**

```yaml
PORT: 8080

HTTP_WORKERS: 2

PROXY_PART: https://ytproxy.local.domain.com

CAPTCHA_BASE_URL: https://api.capmonster.cloud/
CAPTCHA_API_KEY: INSERT_HERE

API_URL: https://ytapi.local.domain.com

FRONTEND_URL: https://yt.local.domain.com

COMPROMISED_PASSWORD_CHECK: true

DISABLE_REGISTRATION: false

FEED_RETENTION: 30

# Hibernate properties
hibernate.connection.url: jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class: org.postgresql.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username: user
hibernate.connection.password: password
```

**Nginx proxy manager:**

NginxPM has SSL via cloudflare and a domain that i own. I have domain.com and local.domain.com (for internal use cases).
I use pihole to create DNS (yt.local.domain.com that has the ip of the nginxproxymanager). this way, instead of ip:port i can go to yt.local.domain.com and SSL works and all that jazz.

The 8118 ports are just ports i *think* are the correct ports. I am clueless on how to make this work.

```yaml
yt.local.domain.com: 192.168.2.x:9005
ytapi.local.domain.com: 192.168.2.x:8118
ytproxy.local.domain.com: 192.168.2.x:8118
```

The issue i have is like mentioned above, when i go to `yt.local.domain.com` I see piped, and the trending page and all. clicking a video works. However, trying to register a user it says "The username you have used is already taken.". 

This is like mentioned a fresh install, and i did not create an account before this. However, i did create an account on public instance (i believe kavin.piped.works or something similar).

Also, I see that when i go to preferences, i have the following setting: 

```
Instance Selection: kavin.rocks (official)
```

Does this means my instance is not local and it is using a public instance?
