### ISSUE TITLE
Docker containers get restarted periodically

### ISSUE THREAD

**Issue by M-Stenzel** [TeamPiped/Piped#2965]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I realised that the containers (backend, frontend & proxy) get restarted periodically (after some hours up to some days).

The services run, but I wonder what makes the containers restart? I would like someone to verify that this is not related to my very own instance.

### To Reproduce

1. Run "docker-compose -f /usr/local/Piped-Docker/docker-compose.yml -p piped up -d"

2.  After some days check with "docker container ls"

3. Find this output:

```
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS                 PORTS                                       NAMES
89dd128c6d5a   1337kavin/piped:latest            "/hotspot-entrypoint…"   4 hours ago     Up 4 hours (healthy)   8080/tcp                                    piped-backend
ed1eeea8ce36   1337kavin/piped-frontend:latest   "ash -c 'sed -i s/pi…"   28 hours ago    Up 28 hours            80/tcp                                      piped-frontend
43a821248a39   1337kavin/piped-proxy:latest      "/app/piped-proxy"       28 hours ago    Up 28 hours            8080/tcp                                    piped-proxy
```

### Expected behavior

The containers should be up the same period of time that corresponds to the "docker-compose -f /usr/local/Piped-Docker/docker-compose.yml -p piped up -d" command

### Browser, and OS with Version.

Docker version 20.10.12

docker-compose.yml:

```
version: "3"

services:
    pipedfrontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        depends_on:
            - piped
        container_name: piped-frontend
        entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/pipedapi.xy-space.de/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        environment:
            - UDS=1
        volumes:
            - piped-proxy:/app/socket
        container_name: piped-proxy
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        volumes:
            - ./config/config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        container_name: piped-backend
    nginx:
        image: nginx:mainline-alpine
        restart: unless-stopped
        ports:
            - "7080:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
            - ./config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
            - ./config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
            - ./config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
            - piped-proxy:/var/run/ytproxy
        container_name: nginx
        depends_on:
            - piped
            - piped-proxy
            - pipedfrontend
    postgres:
        image: postgres:15
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: postgres
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/timezone:/etc/timezone:ro
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_INCLUDE_RESTARTING=true
        container_name: watchtower
        command: piped-frontend piped-backend piped-proxy varnish nginx postgres watchtower
volumes:
    piped-proxy: null
```

Other (non Piped) containers have run for weeks without restart.

This is a Linux OS running on Intel hardware.

### Additional context

Thank you for your help!
