### ISSUE TITLE
how to delete a user ?

### ISSUE THREAD

**Issue by fariszr** [TeamPiped/Piped#732]
i create a user on my own instance, and then i forgot the password 
i deleted the database, and still it says the user is used.

i created a user locally and then tried it on another instance with the same password and it worked, is there some kind of federation in the users ? i see ipfs mentioned in the readme however there are no details what it does.
the projects documentation needs a bit more work in general.

**Comment by FireMasterK** [comment]
> i deleted the database, and still it says the user is used

You likely didn't delete the database properly.
Correct steps:
```
cd Piped-Docker
docker-compose down
rm -rf data
docker-compose up -d
```
> i created a user locally and then tried it on another instance with the same password and it worked

That's literally impossible unless you accidentally on that instance with the same password and username.

> is there some kind of federation in the users

There is none

> ipfs mentioned in the readme however there are no details what it does

It's used to host the website at: ipns://piped-ipfs.kavin.rocks

In the future, there are plans to federate YouTube data between Piped instances (and maybe even other frontends)

**Comment by fariszr** [comment]
> 

i did exactly that, and remove all the containers too.
and it still shows the user is taken for some reason.

i am using a custom installation, without the helper script as i have an existing reverse proxy.
i'm going to submit a PR to the documentation on how to setup piped using compose only.

**Comment by FireMasterK** [comment]
> i am using a custom installation, without the helper script as i have an existing reverse proxy

https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-nginx-aio-script is meant for installations where you already have your own reverse proxy, perhaps this could be made clearer in the future

> also for some reason my instance is still using kavin.rocks proxy instead of my own.
should i open a separate issue for this

No, that's a configuration error on your part, the script linked above configures everything nicely.

**Comment by fariszr** [comment]
Where is the error exactly ?

## Docker-compose.yml
```
version: '3.3'

networks:
  default:
  web:
    external: true

services:

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=DBPASSWORD
    container_name: postgres

  piped-api:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - ./config.properties:/app/config.properties:ro
    # ports:
    #   - 127.0.0.1:8080:8080
    depends_on:
      - postgres

  varnish:
    image: varnish:7.0-alpine
    restart: unless-stopped
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    container_name: piped-varnish
    depends_on:
      - piped-api
    healthcheck:
      test: ash -c "wget --no-verbose --tries=1 --spider 127.0.0.1:80/feed ||
        (varnishreload && exit 1)"
      interval: 10s
      timeout: 10s
      retries: 1
    networks:
      - web
      - default

  ytproxy:
    image: 1337kavin/ytproxy:latest
    restart: unless-stopped
    volumes:
      - ytproxy:/app/socket
    container_name: ytproxy

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    container_name: piped-proxy
    # ports:
    #   - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
      - ytproxy:/var/run/ytproxy
    depends_on:
      - ytproxy
    networks:
      - web
      - default

  piped-frontend:
    image: 1337kavin/piped-frontend:latest
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:80:80
    depends_on:
      - piped-api
      - nginx
    container_name: piped-frontend
    entrypoint: ash -c 'sed -i s/pipedapi.text/apipiped.HOSTNAME/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    networks:
      - web
      - default
volumes:
  ytproxy: null
```

## ytproxy.conf
```
server {
    listen 84;
    server_name proxy-piped.HOSTNAME;

    location ~ (/videoplayback|/api/v4/|/api/manifest/) {
        include snippets/ytproxy.conf;
        add_header Cache-Control private always;
    }

    location / {
        include snippets/ytproxy.conf;
        add_header Cache-Control "public, max-age=604800";
    }
}
```

## nginx.conf
```
user root;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;


events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nodelay on;

    keepalive_timeout 65;

    gzip on;

    include /etc/nginx/conf.d/*.conf;
}
```

## config.proprties
```
# The port to Listen on.
PORT: 8080

# The number of workers to use for the server
HTTP_WORKERS: 2

# Proxy
PROXY_PART: https://proxy-piped.HOSTNAME

# Outgoing HTTP Proxy - eg: 127.0.0.1:8118
#HTTP_PROXY: 127.0.0.1:8118

# Captcha Parameters
CAPTCHA_BASE_URL: https://api.capmonster.cloud/
CAPTCHA_API_KEY: INSERT_HERE

# Public API URL
API_URL: https://apipiped.HOSTNAME

# Public Frontend URL
FRONTEND_URL: https://piped.HOSTNAME

# Enable haveibeenpwned compromised password API
COMPROMISED_PASSWORD_CHECK: true

# Disable Registration
DISABLE_REGISTRATION: true

# Hibernate properties
hibernate.connection.url: jdbc:postgresql://postgres:5432/piped
hibernate.connection.driver_class: org.postgresql.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
hibernate.connection.username: piped
hibernate.connection.password: DBPASSWORD
```
even though registration is disabled, it still works for some reason.

> https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-nginx-aio-script is meant for installations where you already have your own reverse proxy, perhaps this could be made clearer in the future

i like to stay with a simple compose file. 
also for the config, i only used nginx for ytproxy, all other services are proxied directly by the reverse proxy.
